apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: default
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: ghcr.io/dankirkham/website:release
        ports:
        - containerPort: 80
          name: website-web-svc
      imagePullSecrets:
      - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: website-internal-service
  namespace: default
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  namespace: default
spec:
  rules:
  - host: ae4ta.com
    http:
      paths:
      - backend:
          serviceName: website-internal-service
          servicePort: 80
